title: jemmycslearn
author: jemmY
email: jemmy9211@gmail.com
description:
  this means to ignore newlines until "show_exerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
show_excerpts:
  set to true to show excerpts on the homepage
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Jemmy Chen
  tagline: NCHU CSE
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: games
  navigation:
      - title: AboutMe
        url: "/Writer"
      - title: Aboutblog
        url: "/about"
      - title: update records
        url: "/update"
  # generate social links in footer
  social_links:
    # twitter:
    github:  jemmy9211
    #linkedIn: in/
    rss: rss
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
 #mastodon:
    # - username: jekyll
     #  instance: example.com
    # - username: jekyll2
     #  instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

  #Build settings


plugins:
  - jekyll-seo-tag
  #- jekyll-feed
