# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"  # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "zh-TW"
title                    : "Jemmy Blog"
title_separator          : "//"
subtitle                 : "about science"  # site tagline that appears below site title in masthead
name                     : "JemmyChen"
description              : "An website about my work and life"
url                      : "https://jemmy9211.github.io"  # the base hostname & protocol for your site
baseurl                  : ""  # the subpath of your site, e.g. "/blog"
repository               : "jemmy9211/jemmy9211.github.io"  # GitHub username/repo-name
teaser                   : "/assets/teaser.jpeg"  # path of fallback teaser image
logo                     : ""  # path of logo image to display in the masthead
masthead_title           : "Jemmy Blog"  # overrides the website title displayed in the masthead
breadcrumbs              : true  # true, false (default)
words_per_minute         : 150

comments:
  provider               : "disqus"  # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : "jemmycslearn"

staticman:
  allowedFields          :  # ['name', 'email', 'url', 'message']
  branch                 :  # "master"
  commitMessage          :  # "New comment by {fields.name}"
  filename               :  # comment-{@timestamp}
  format                 :  # "yml"
  moderation             :  # true
  path                   :  # "/_data/comments/{options.slug}" (default)
  requiredFields         :  # ['name', 'email', 'message']
  transforms:
    email                :  # "md5"
  generatedFields:
    date:
      type               :  # "date"
      options:
        format           :  # "iso8601" (default), "timestamp-seconds", "timestamp-milliseconds123"
  endpoint               :  # URL of your own deployment with trailing slash

reCaptcha:
  siteKey                :
  secret                 :

atom_feed:
  path                   :  # blank (default) uses feed.xml

search                   : true  # true, false (default)
search_full_content      : true  # true, false (default)
search_provider          :  # lunr (default), algolia, google

algolia:
  application_id         :  # YOUR_APPLICATION_ID
  index_name             :  # YOUR_INDEX_NAME
  search_only_api_key    :  # YOUR_SEARCH_ONLY_API_KEY
  powered_by             :  # true (default), false

google:
  search_engine_id       : 013216236818033654223:ryh17ow4wo8  # YOUR_SEARCH_ENGINE_ID
  instant_search         : true  # false (default), true

# SEO Related
google_site_verification : HTntN0a-6o-EnteW8EGLZU1rTRNeAevxDzoTLQAGrZc
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :

facebook:
  username               : "陳冠軒"
  app_id                 :
  publisher              : "facebook"

og_image                 : "/assets/opimg.png"  # Open Graph/Twitter default site image

social:
  type                   :  # Person or Organization (defaults to Person)
  name                   :  # If the user or organization name differs from the site's name
  links:
    - label: "CV"
      icon: "fas fa-fw fa-link"
      url: "https://jemmy9211.github.io/assets/Jemmy_s_Software_Engineering_Resume.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jemmy9211"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jemmy_921"
    - label: "天氣預報網頁"
      icon: "fas fa-fw fa-link"
      url: "https://jemmy9211.github.io/WeatherVue/"
    - label: "美股看盤網頁"
      icon: "fas fa-fw fa-link"
      url: "https://jemmy9211.github.io/StockVue/"

# Analytics
analytics:
  provider               : false  # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         :  # true, false (default)

# Site Author
author:
  name                   : "JemmyChen"
  avatar                 : "/assets/jemmy.jpg"
  bio                    : "紀錄一些學習的過程和筆記"
  location               : "Taiwan"
  email                  : ""
  links:
    - label: "CV"
      icon: "fas fa-fw fa-link"
      url: "https://jemmy9211.github.io/assets/Jemmy_s_Software_Engineering_Resume.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jemmy9211"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jemmy_921"
    - label: "天氣預報網頁"
      icon: "fas fa-fw fa-link"
      url: "https://jemmy9211.github.io/WeatherVue/"
    - label: "美股看盤網頁"
      icon: "fas fa-fw fa-link"
      url: "https://jemmy9211.github.io/StockVue/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/jemmy9211

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs  # ignore Minimal Mistakes /docs
  - /test  # ignore Minimal Mistakes /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed  # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5  # amount of posts to show
paginate_path: /page:num/
timezone:  # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: posts
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
