# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme
# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default"  # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "zh-TW"
title                    : "Jemmy Blog | 陳冠軒個人網站"
title_separator          : "//"
subtitle                 : "about science"  # site tagline that appears below site title in masthead
name                     : "陳冠軒 Jemmy Chen"
description              : "陳冠軒 (Jemmy Chen) 的個人部落格 - 分享科學知識、程式設計、軟體工程和生活體驗。技術筆記與學習心得分享。"
url                      : "https://jemmy9211.github.io"  # the base hostname & protocol for your site
baseurl                  : ""  # the subpath of your site, e.g. "/blog"
repository               : "jemmy9211/jemmy9211.github.io"  # GitHub username/repo-name
teaser                   : "/assets/images/teaser.jpeg"  # path of fallback teaser image
logo                     : ""  # path of logo image to display in the masthead
masthead_title           : "Jemmy Blog | 陳冠軒"  # overrides the website title displayed in the masthead
breadcrumbs              : true  # true, false (default)
words_per_minute         : 200  # 提高閱讀速度估算
date_format              : "%Y-%m-%d"  # 統一日期格式

# Comments
comments:
  provider               : "disqus"  # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "custom"
  disqus:
    shortname            : "jemmycslearn"

# reCaptcha (if needed for forms)
reCaptcha:
  siteKey                : ""
  secret                 : ""

# Feed
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : false  # 確保 RSS feed 可用

# Search
search                   : true  # true, false (default)
search_full_content      : true  # true, false (default)
search_provider          : "lunr"  # lunr (default), algolia, google

# Google Search (備用選項)
google:
  search_engine_id       : "013216236818033654223:ryh17ow4wo8"  # YOUR_SEARCH_ENGINE_ID
  instant_search         : true  # false (default), true

# SEO Related
google_site_verification : "HTntN0a-6o-EnteW8EGLZU1rTRNeAevxDzoTLQAGrZc"
bing_site_verification   : ""
yandex_site_verification : ""
naver_site_verification  : ""

# Social Sharing
twitter:
  username               : ""
  card                   : "summary_large_image"  # 改善 Twitter 卡片顯示

facebook:
  username               : "陳冠軒"
  app_id                 : ""
  publisher              : "facebook"

og_image                 : "/assets/images/opimg.jpg"  # Open Graph/Twitter default site image
og_type                  : "website"  # 明確指定 Open Graph 類型

# Social Links
social:
  type                   : "Person"  # Person or Organization (defaults to Person)
  name                   : "JemmyChen"  # If the user or organization name differs from the site's name
  links:
    - "https://github.com/jemmy9211"
    - "https://instagram.com/jemmy_921"

# Analytics
analytics:
  provider               : "google-gtag"  # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-XXXXXXXXXX"  # 請更換為你的實際 Google Analytics ID
    anonymize_ip         : true  # 啟用 IP 匿名化以符合 GDPR

# Site Author
author:
  name                   : "陳冠軒 Jemmy Chen"
  avatar                 : "/assets/images/jemmy.jpg"
  bio                    : "資訊科學研究者"
  location               : "Taiwan"
  email                  : "jemmy9211@gmail.com"
  links:
    - label: "履歷 CV"
      icon: "fas fa-fw fa-file-pdf"
      url: "https://jemmy9211.github.io/assets/Jemmy_s_Software_Engineering_Resume.pdf"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jemmy9211"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/jemmy_921"
    - label: "天氣預報網頁"
      icon: "fas fa-fw fa-cloud-sun"
      url: "https://jemmy9211.github.io/WeatherVue/"
    - label: "美股看盤網頁"
      icon: "fas fa-fw fa-chart-line"
      url: "https://jemmy9211.github.io/StockVue/"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jemmy9211"
    - label: "RSS Feed"
      icon: "fas fa-fw fa-rss-square"
      url: "/feed.xml"

# Reading Files
include:
  - .htaccess
  - _pages
  - _redirects  # 支援 Netlify redirects (如果需要的話)

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs  # ignore Minimal Mistakes /docs
  - /test  # ignore Minimal Mistakes /test
  - "*.gem"
  - ".jekyll-cache"

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    line_numbers: true  # 顯示程式碼行號
    block:
      line_numbers: true
      start_line: 1

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed  # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 8  # 增加每頁文章數量以減少頁面數
paginate_path: /page:num/
timezone: "Asia/Taipei"  # 設定台灣時區

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag  # 加強 SEO

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# Collections (如果需要組織其他類型的內容)
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# HTML Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [html, head, body]
  blanklines: false
  profile: false
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
      toc: true  # 自動產生目錄
      toc_sticky: true  # 目錄固定在側邊
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: false
      share: true

# Site-wide settings for better performance and SEO
future: false  # 不發布未來日期的文章
show_drafts: false  # 不顯示草稿
limit_posts: 0  # 不限制文章數量
highlighter_style: "github"  # 程式碼高亮樣式

# Teaser overlay color (used with `overlay_image`)
teaser_color:

# Site Teaser in Masthead
#
# Default is `true` which uses the `header_image`.
# `false` will use the `site_logo` instead.
masthead_teaser: true

# Meta Description
#
# Used by search engines. Can be set on a page-by-page basis.
#
# For specifying the image that will be used when sharing a link to your site.
#
# Example:
# - og_image: "/assets/images/page-meta-image.png"
#
# For specifying the default image that will be used when sharing a link to a page.
# This is a fallback and can be overridden on a page-by-page basis.
